version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "127.0.0.1:8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "127.0.0.1:8888:8888"
    depends_on:
      - eureka-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - JWT_SECRET=${JWT_SECRET}

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - postgres
      - kafka
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}

  auction-service:
    build: ./auction-service
    container_name: auction-service
    ports:
      - "127.0.0.1:8082:8082"
    depends_on:
      - postgres
      - kafka
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  bidding-service:
    build: ./bidding-service
    container_name: bidding-service
    ports:
      - "127.0.0.1:8083:8083"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "127.0.0.1:8084:8084"
    depends_on:
      - kafka
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

volumes:
    postgres_data: