server:
  port: 9090

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - AuthenticationFilter
            - id: auction-service
              uri: lb://AUCTION-SERVICE
              predicates:
                - Path=/api/auctions/**
              filters:
                - AuthenticationFilter
            - id: bidding-service
              uri: lb://BIDDING-SERVICE
              predicates:
                - Path=/api/bids/**
              filters:
                - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: ${JWT_SECRET}