server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auction_db
    username: postgres
    password: atharv
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          create_namespaces: true
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/