server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/auction_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:29092

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRY}